### ISSUE TITLE
Please provide your book in PDF, or epub 

### ISSUE THREAD

**Issue by saleh-mir** [chrisconlan/algorithmic-trading-with-python#2]
I just wanted to say I looked to buy your book but I'm not interested a paperback version. Please consider other options (it's 2020!)

**Comment by geofffoster** [comment]
I don't think Chris wants his book pirated

**Comment by saleh-mir** [comment]
@geofffoster yes, ebooks get pirated easier, they also sell easier

**Comment by chrisconlan** [comment]
Thanks Geoff. It’s also a formatting issue. Kindle books are notoriously bad at formatting math and code. I want to make sure the final product is high quality even if it limits my distribution methods.

**Comment by saleh-mir** [comment]
@chrisconlan there are services that allow selling PDFs. That way the formatting would stay the same.
