### ISSUE TITLE
Listings 7_1 and 7_2

### ISSUE THREAD

**Issue by geofffoster** [chrisconlan/algorithmic-trading-with-python#3]
Is it possible to have  wrapping code for these two examples, reading in an example series and relevant plots?

**Comment by chrisconlan** [comment]
The code that generates those plots is not publication quality, so not at this time. I'll keep that in mind for future editions.

**Comment by chrisconlan** [comment]
I would also welcome any PR that attempts to visualize those concepts in a way that is helpful to readers, above and beyond what I have published in the book.
