### ISSUE TITLE
Listing 4.7

### ISSUE THREAD

**Issue by jobquiroz** [chrisconlan/algorithmic-trading-with-python#5]
Hello,
I'm trying to run the simulator example usage in listing 4.7 but I get a "Value error: Lenghts must match"

When I print the lengths of the variables `c_series` and `p_series` in `_compute_equity_series` (within the `PortfolioHistory class`) I indeed find out that they are different (1280 vs 2495). 

I think I have all set up correctly, my example usage of PortfolioHistory runs correctly.

Do you have any advice?

Thank you.
The book is great.

**Comment by chrisconlan** [comment]
Hi Job, please try running the `simulate_portfolio.py` script directly from the GitHub repo. It is the same as Listing 4.7, and I just verified it works on a clean copy of the repo. 

https://github.com/chrisconlan/algorithmic-trading-with-python/blob/master/src/simulate_portfolio.py

**Comment by jobquiroz** [comment]
Thank you, that actually worked pretty well!
