### ISSUE TITLE
7_2_computing_triple_barrier_labels.py

### ISSUE THREAD

**Issue by theAfricanQuant** [chrisconlan/algorithmic-trading-with-python#8]
Hello Chris
I bought your book sometime last year.

You didn't give us you example on how to use the triple barrier based on the codes you provided. I can see there are two functions if you can just explain what they are for.
I know the "calculate_labels" requires the " compute_triple_barrier_labels" but the output from the two look alike when I ran them one by one.

I have read de Prado's works and compared to his codes yours were simpler to run and test.

Thanks

**Comment by chrisconlan** [comment]
Thanks very much for checking out the book. The `calculate_labels` function is just a wrapper around `compute_triple_barrier_labels` the handles some of the more verbose arguments. You are correct.
